<?php

namespace ContainerIr63kLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AQLsc69Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aQLsc69' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aQLsc69'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'group' => ['privates', '.errored..service_locator.aQLsc69.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.aQLsc69": it references class "App\\Entity\\Group" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'group' => 'App\\Entity\\Group',
        ]);
    }
}
