<?php

namespace ContainerIr63kLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YTJ74cXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YTJ74cX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YTJ74cX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BuildingController::createAction' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\BuildingController::detailAction' => ['privates', '.service_locator.pMB7H2q', 'get_ServiceLocator_PMB7H2qService', true],
            'App\\Controller\\BuildingController::editAction' => ['privates', '.service_locator.bRtVdcC', 'get_ServiceLocator_BRtVdcCService', true],
            'App\\Controller\\BuildingController::listAction' => ['privates', '.service_locator.hdAuqDy', 'get_ServiceLocator_HdAuqDyService', true],
            'App\\Controller\\GroupController::createAction' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GroupController::detailAction' => ['privates', '.service_locator.lK5cIE4', 'get_ServiceLocator_LK5cIE4Service', true],
            'App\\Controller\\GroupController::editAction' => ['privates', '.service_locator.aQLsc69', 'get_ServiceLocator_AQLsc69Service', true],
            'App\\Controller\\GroupController::listAction' => ['privates', '.service_locator.5RqRLaq', 'get_ServiceLocator_5RqRLaqService', true],
            'App\\Controller\\RoomController::createAction' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RoomController::detailAction' => ['privates', '.service_locator.UPqJ.1L', 'get_ServiceLocator_UPqJ_1LService', true],
            'App\\Controller\\RoomController::editAction' => ['privates', '.service_locator.2G4LaC7', 'get_ServiceLocator_2G4LaC7Service', true],
            'App\\Controller\\RoomController::listAction' => ['privates', '.service_locator._mkxdFJ', 'get_ServiceLocator_MkxdFJService', true],
            'App\\Controller\\RoomController::requestAction' => ['privates', '.service_locator.X3m7mKa', 'get_ServiceLocator_X3m7mKaService', true],
            'App\\Controller\\RoomController::requestDecisionAction' => ['privates', '.service_locator.X3m7mKa', 'get_ServiceLocator_X3m7mKaService', true],
            'App\\Controller\\RoomController::reservationAction' => ['privates', '.service_locator.HmbV3zW', 'get_ServiceLocator_HmbV3zWService', true],
            'App\\Controller\\RoomController::reservationDecisionAction' => ['privates', '.service_locator.HmbV3zW', 'get_ServiceLocator_HmbV3zWService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\BuildingController:createAction' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\BuildingController:detailAction' => ['privates', '.service_locator.pMB7H2q', 'get_ServiceLocator_PMB7H2qService', true],
            'App\\Controller\\BuildingController:editAction' => ['privates', '.service_locator.bRtVdcC', 'get_ServiceLocator_BRtVdcCService', true],
            'App\\Controller\\BuildingController:listAction' => ['privates', '.service_locator.hdAuqDy', 'get_ServiceLocator_HdAuqDyService', true],
            'App\\Controller\\GroupController:createAction' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GroupController:detailAction' => ['privates', '.service_locator.lK5cIE4', 'get_ServiceLocator_LK5cIE4Service', true],
            'App\\Controller\\GroupController:editAction' => ['privates', '.service_locator.aQLsc69', 'get_ServiceLocator_AQLsc69Service', true],
            'App\\Controller\\GroupController:listAction' => ['privates', '.service_locator.5RqRLaq', 'get_ServiceLocator_5RqRLaqService', true],
            'App\\Controller\\RoomController:createAction' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RoomController:detailAction' => ['privates', '.service_locator.UPqJ.1L', 'get_ServiceLocator_UPqJ_1LService', true],
            'App\\Controller\\RoomController:editAction' => ['privates', '.service_locator.2G4LaC7', 'get_ServiceLocator_2G4LaC7Service', true],
            'App\\Controller\\RoomController:listAction' => ['privates', '.service_locator._mkxdFJ', 'get_ServiceLocator_MkxdFJService', true],
            'App\\Controller\\RoomController:requestAction' => ['privates', '.service_locator.X3m7mKa', 'get_ServiceLocator_X3m7mKaService', true],
            'App\\Controller\\RoomController:requestDecisionAction' => ['privates', '.service_locator.X3m7mKa', 'get_ServiceLocator_X3m7mKaService', true],
            'App\\Controller\\RoomController:reservationAction' => ['privates', '.service_locator.HmbV3zW', 'get_ServiceLocator_HmbV3zWService', true],
            'App\\Controller\\RoomController:reservationDecisionAction' => ['privates', '.service_locator.HmbV3zW', 'get_ServiceLocator_HmbV3zWService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\BuildingController::createAction' => '?',
            'App\\Controller\\BuildingController::detailAction' => '?',
            'App\\Controller\\BuildingController::editAction' => '?',
            'App\\Controller\\BuildingController::listAction' => '?',
            'App\\Controller\\GroupController::createAction' => '?',
            'App\\Controller\\GroupController::detailAction' => '?',
            'App\\Controller\\GroupController::editAction' => '?',
            'App\\Controller\\GroupController::listAction' => '?',
            'App\\Controller\\RoomController::createAction' => '?',
            'App\\Controller\\RoomController::detailAction' => '?',
            'App\\Controller\\RoomController::editAction' => '?',
            'App\\Controller\\RoomController::listAction' => '?',
            'App\\Controller\\RoomController::requestAction' => '?',
            'App\\Controller\\RoomController::requestDecisionAction' => '?',
            'App\\Controller\\RoomController::reservationAction' => '?',
            'App\\Controller\\RoomController::reservationDecisionAction' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BuildingController:createAction' => '?',
            'App\\Controller\\BuildingController:detailAction' => '?',
            'App\\Controller\\BuildingController:editAction' => '?',
            'App\\Controller\\BuildingController:listAction' => '?',
            'App\\Controller\\GroupController:createAction' => '?',
            'App\\Controller\\GroupController:detailAction' => '?',
            'App\\Controller\\GroupController:editAction' => '?',
            'App\\Controller\\GroupController:listAction' => '?',
            'App\\Controller\\RoomController:createAction' => '?',
            'App\\Controller\\RoomController:detailAction' => '?',
            'App\\Controller\\RoomController:editAction' => '?',
            'App\\Controller\\RoomController:listAction' => '?',
            'App\\Controller\\RoomController:requestAction' => '?',
            'App\\Controller\\RoomController:requestDecisionAction' => '?',
            'App\\Controller\\RoomController:reservationAction' => '?',
            'App\\Controller\\RoomController:reservationDecisionAction' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
