<?php

namespace ContainerIr63kLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HmbV3zWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HmbV3zW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HmbV3zW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'room' => ['privates', '.errored..service_locator.HmbV3zW.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.HmbV3zW": it references class "App\\Entity\\Room" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'room' => 'App\\Entity\\Room',
        ]);
    }
}
