<?php

namespace ContainerIr63kLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MkxdFJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._mkxdFJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._mkxdFJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService', true],
        ], [
            'roomRepository' => 'App\\Repository\\RoomRepository',
        ]);
    }
}
