<?php

namespace ContainerIr63kLv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoom4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X3m7mKa.App\Entity\Room' shared service.
     *
     * @return \App\Entity\Room
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.X3m7mKa": it references class "App\\Entity\\Room" but no such service exists.');
    }
}
