<?php

namespace ContainerEgqQ5Br;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QcEVK4yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qcEVK4y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qcEVK4y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BuildingController::createAction' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\BuildingController::detailAction' => ['privates', '.service_locator.0Ew4wgn', 'get_ServiceLocator_0Ew4wgnService', true],
            'App\\Controller\\BuildingController::editAction' => ['privates', '.service_locator.w2NzbQn', 'get_ServiceLocator_W2NzbQnService', true],
            'App\\Controller\\BuildingController::listAction' => ['privates', '.service_locator.8inku65', 'get_ServiceLocator_8inku65Service', true],
            'App\\Controller\\GroupController::createAction' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\GroupController::detailAction' => ['privates', '.service_locator.z0pCzx9', 'get_ServiceLocator_Z0pCzx9Service', true],
            'App\\Controller\\GroupController::editAction' => ['privates', '.service_locator.Ox1J.eW', 'get_ServiceLocator_Ox1J_EWService', true],
            'App\\Controller\\GroupController::listAction' => ['privates', '.service_locator.Rze8UIU', 'get_ServiceLocator_Rze8UIUService', true],
            'App\\Controller\\RoomController::createAction' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\RoomController::detailAction' => ['privates', '.service_locator.BE26jFD', 'get_ServiceLocator_BE26jFDService', true],
            'App\\Controller\\RoomController::editAction' => ['privates', '.service_locator.8tRcaPy', 'get_ServiceLocator_8tRcaPyService', true],
            'App\\Controller\\RoomController::listAction' => ['privates', '.service_locator.QZ4UITY', 'get_ServiceLocator_QZ4UITYService', true],
            'App\\Controller\\RoomController::requestAction' => ['privates', '.service_locator.7HKXV.l', 'get_ServiceLocator_7HKXV_LService', true],
            'App\\Controller\\RoomController::reservationAction' => ['privates', '.service_locator.YroJ7yu', 'get_ServiceLocator_YroJ7yuService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.Dby0_1s', 'get_ServiceLocator_Dby01sService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BuildingController:createAction' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\BuildingController:detailAction' => ['privates', '.service_locator.0Ew4wgn', 'get_ServiceLocator_0Ew4wgnService', true],
            'App\\Controller\\BuildingController:editAction' => ['privates', '.service_locator.w2NzbQn', 'get_ServiceLocator_W2NzbQnService', true],
            'App\\Controller\\BuildingController:listAction' => ['privates', '.service_locator.8inku65', 'get_ServiceLocator_8inku65Service', true],
            'App\\Controller\\GroupController:createAction' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\GroupController:detailAction' => ['privates', '.service_locator.z0pCzx9', 'get_ServiceLocator_Z0pCzx9Service', true],
            'App\\Controller\\GroupController:editAction' => ['privates', '.service_locator.Ox1J.eW', 'get_ServiceLocator_Ox1J_EWService', true],
            'App\\Controller\\GroupController:listAction' => ['privates', '.service_locator.Rze8UIU', 'get_ServiceLocator_Rze8UIUService', true],
            'App\\Controller\\RoomController:createAction' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\RoomController:detailAction' => ['privates', '.service_locator.BE26jFD', 'get_ServiceLocator_BE26jFDService', true],
            'App\\Controller\\RoomController:editAction' => ['privates', '.service_locator.8tRcaPy', 'get_ServiceLocator_8tRcaPyService', true],
            'App\\Controller\\RoomController:listAction' => ['privates', '.service_locator.QZ4UITY', 'get_ServiceLocator_QZ4UITYService', true],
            'App\\Controller\\RoomController:requestAction' => ['privates', '.service_locator.7HKXV.l', 'get_ServiceLocator_7HKXV_LService', true],
            'App\\Controller\\RoomController:reservationAction' => ['privates', '.service_locator.YroJ7yu', 'get_ServiceLocator_YroJ7yuService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.Dby0_1s', 'get_ServiceLocator_Dby01sService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BuildingController::createAction' => '?',
            'App\\Controller\\BuildingController::detailAction' => '?',
            'App\\Controller\\BuildingController::editAction' => '?',
            'App\\Controller\\BuildingController::listAction' => '?',
            'App\\Controller\\GroupController::createAction' => '?',
            'App\\Controller\\GroupController::detailAction' => '?',
            'App\\Controller\\GroupController::editAction' => '?',
            'App\\Controller\\GroupController::listAction' => '?',
            'App\\Controller\\RoomController::createAction' => '?',
            'App\\Controller\\RoomController::detailAction' => '?',
            'App\\Controller\\RoomController::editAction' => '?',
            'App\\Controller\\RoomController::listAction' => '?',
            'App\\Controller\\RoomController::requestAction' => '?',
            'App\\Controller\\RoomController::reservationAction' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BuildingController:createAction' => '?',
            'App\\Controller\\BuildingController:detailAction' => '?',
            'App\\Controller\\BuildingController:editAction' => '?',
            'App\\Controller\\BuildingController:listAction' => '?',
            'App\\Controller\\GroupController:createAction' => '?',
            'App\\Controller\\GroupController:detailAction' => '?',
            'App\\Controller\\GroupController:editAction' => '?',
            'App\\Controller\\GroupController:listAction' => '?',
            'App\\Controller\\RoomController:createAction' => '?',
            'App\\Controller\\RoomController:detailAction' => '?',
            'App\\Controller\\RoomController:editAction' => '?',
            'App\\Controller\\RoomController:listAction' => '?',
            'App\\Controller\\RoomController:requestAction' => '?',
            'App\\Controller\\RoomController:reservationAction' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
