<?php

namespace ContainerEgqQ5Br;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8tRcaPyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8tRcaPy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8tRcaPy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'room' => ['privates', '.errored..service_locator.8tRcaPy.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.8tRcaPy": it references class "App\\Entity\\Room" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'room' => 'App\\Entity\\Room',
        ]);
    }
}
