<?php

namespace ContainerEgqQ5Br;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroup2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.z0pCzx9.App\Entity\Group' shared service.
     *
     * @return \App\Entity\Group
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.z0pCzx9": it references class "App\\Entity\\Group" but no such service exists.');
    }
}
