<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIr63kLv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIr63kLv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIr63kLv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIr63kLv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIr63kLv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ir63kLv',
    'container.build_id' => '4749c4ae',
    'container.build_time' => 1664574554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIr63kLv');
